packages:
  #| all direct packages
  # - "Getting_Started/first-app"
  #| all packages in direct subdirs of packages/
  - "Course_Assignments/*"
  - "Course_Project/*"
  - "course-practice/*"
  # - 'packages/*'
  #| all packages in subdirs of components/
  #* - 'components/**'
  #| exclude packages that are inside test directories
  #* - '!**/test/**'
