packages:
  #| all direct packages
  - "Course_Project"
  - "Getting_Started/first-app"
  #| all packages in direct subdirs of packages/
  - "Course_Assignments/*"
  #* - 'packages/*'
  #| all packages in subdirs of components/
  #* - 'components/**'
  #| exclude packages that are inside test directories
  #* - '!**/test/**'
